extends Node

var CARD_DB = {
	"Wolf": {'Name': 'Wolf', 'Rarity': 'C', 'Cost': 'GG', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '2', 'HP': '5', 'Ability': '', 'Art': 'Sprites/New_Sprites/Wolf.png', 'Ability_Function': '', 'Ability_Parameters': '', 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Witch": {'Name': 'Witch', 'Rarity': 'U', 'Cost': 'AG', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '1', 'HP': '3', 'Ability': 'On Play: Draw 1 card', 'Art': 'Sprites/New_Sprites/Witch.png', 'Ability_Function': 'Draw', 'Ability_Parameters': 1, 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Index": {'Name': 'Index', 'Rarity': 'C', 'Cost': 'A', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Draw 1 card', 'Art': 'Sprites/New_Sprites/Think.png', 'Ability_Function': 'Draw', 'Ability_Parameters': 1, 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Fulmen": {'Name': 'Fulmen', 'Rarity': 'U', 'Cost': 'A', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Deal 3 Damage', 'Art': 'Sprites/New_Sprites/Bolt.png', 'Ability_Function': 'Damage', 'Ability_Parameters': 3, 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Gather Knowledge": {'Name': 'Gather Knowledge', 'Rarity': 'R', 'Cost': 'AAA', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Draw 3 cards', 'Art': 'Sprites/New_Sprites/ThinkBig.png', 'Ability_Function': 'Draw', 'Ability_Parameters': 3, 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Fortify Potion": {'Name': 'Fortify Potion', 'Rarity': 'C', 'Cost': 'AG', 'Class': 'Gen', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Buff target unit +2/+2', 'Art': 'Sprites/New_Sprites/Fortify_Potion.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [2, 2], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Sword": {'Name': 'Sword', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Gen', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Buff a unit +2/+0', 'Art': 'Sprites/Sword.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [2, 0], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Shield": {'Name': 'Shield', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Gen', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Buff a unit +0/+2', 'Art': 'Sprites/New_Sprites/Shield.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [0, 2], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Snake": {'Name': 'Snake', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '1', 'HP': '2', 'Ability': '', 'Art': 'Sprites/New_Sprites/Snake.png', 'Ability_Function': '', 'Ability_Parameters': '', 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Bear": {'Name': 'Bear', 'Rarity': 'R', 'Cost': 'G', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '2', 'HP': '2', 'Ability': '', 'Art': 'Sprites/New_Sprites/Bear.png', 'Ability_Function': '', 'Ability_Parameters': '', 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Wyrm": {'Name': 'Wyrm', 'Rarity': 'C', 'Cost': 'A', 'Class': 'Mge', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': 'Whenever you cast a spell draw 1 card', 'Art': 'Sprites/New_Sprites/Wyrm.png', 'Ability_Function': 'Draw', 'Ability_Parameters': [1, 'CastSpell'], 'Ability_Trigger': 'Trigger', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Turtle": {'Name': 'Turtle', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '0', 'HP': '4', 'Ability': '', 'Art': 'Sprites/New_Sprites/Turtle.png', 'Ability_Function': '', 'Ability_Parameters': '', 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Fulmen Flash": {'Name': 'Fulmen Flash', 'Rarity': 'R', 'Cost': 'AAAA', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Deal 6 Damage', 'Art': 'Sprites/New_Sprites/MegaBolt.png', 'Ability_Function': 'Damage', 'Ability_Parameters': 6, 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"BannerMan": {'Name': 'BannerMan', 'Rarity': 'R', 'Cost': 'GG', 'Class': 'Knt', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': 'All Friendly Units get +1/+1', 'Art': 'Sprites/New_Sprites/BannerMan.png', 'Ability_Function': 'TeamBuff', 'Ability_Parameters': [1, 1], 'Ability_Trigger': 'Static', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Squire": {'Name': 'Squire', 'Rarity': 'U', 'Cost': 'G', 'Class': 'Knt', 'Type': 'Unit', 'Attack': '0', 'HP': '1', 'Ability': 'Target Friendly Unit gets +1/+1', 'Art': 'Sprites/New_Sprites/Squire.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [1, 1], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Fox": {'Name': 'Fox', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Rge', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': 'Thieve 1', 'Art': 'Sprites/New_Sprites/Fox.png', 'Ability_Function': 'Thieve', 'Ability_Parameters': 1, 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"BabyDragon": {'Name': 'BabyDragon', 'Rarity': 'R', 'Cost': 'AAG', 'Class': 'Mge', 'Type': 'Unit', 'Attack': '2', 'HP': '4', 'Ability': 'Deal 3 Damage', 'Art': 'Sprites/New_Sprites/BabyDragon.png', 'Ability_Function': 'Damage', 'Ability_Parameters': 3, 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Owl": {'Name': 'Owl', 'Rarity': 'U', 'Cost': 'A', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': 'Activate: Draw 1 Card', 'Art': 'Sprites/New_Sprites/Owl.png', 'Ability_Function': 'Draw', 'Ability_Parameters': 1, 'Ability_Trigger': 'Select', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Imp": {'Name': 'Imp', 'Rarity': 'U', 'Cost': 'A', 'Class': 'Mge', 'Type': 'Unit', 'Attack': '0', 'HP': '2', 'Ability': 'Deal 1 Damage', 'Art': 'Sprites/New_Sprites/BallImp.png', 'Ability_Function': 'Damage', 'Ability_Parameters': 1, 'Ability_Trigger': 'Select', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Rallier": {'Name': 'Rallier', 'Rarity': 'C', 'Cost': 'G', 'Class': 'Knt', 'Type': 'Unit', 'Attack': '0', 'HP': '2', 'Ability': 'On Play: Rally 1', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Rally', 'Ability_Parameters': 1, 'Ability_Trigger': 'Cast', 'Additional_Costs': 'Merchant', 'Additional_Costs_Parameters': [1]},
	"Arcane Channeler": {'Name': 'Arcane Channeler', 'Rarity': 'C', 'Cost': 'A', 'Class': 'Mge', 'Type': 'Unit', 'Attack': '0', 'HP': '2', 'Ability': 'On Play: Channel 1', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Channel', 'Ability_Parameters': 1, 'Ability_Trigger': 'Cast', 'Additional_Costs': 'Wizard', 'Additional_Costs_Parameters': [1]},
	"Crafty Cutpurse": {'Name': 'Crafty Cutpurse', 'Rarity': 'C', 'Cost': 'GG', 'Class': 'Rge', 'Type': 'Unit', 'Attack': '2', 'HP': '2', 'Ability': 'Thieve 2', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Thieve', 'Ability_Parameters': 2, 'Ability_Trigger': 'Trigger', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Disarm": {'Name': 'Disarm', 'Rarity': 'C', 'Cost': 'A', 'Class': 'Rge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Debuff target unit -4/0', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [-4, 0], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Backstab": {'Name': 'Backstab', 'Rarity': 'U', 'Cost': 'GAA', 'Class': 'Rge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Debuff target unit -2/-4', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [-2, -4], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Back Alley Bully": {'Name': 'Back Alley Bully', 'Rarity': 'R', 'Cost': 'GGG', 'Class': 'Rge', 'Type': 'Unit', 'Attack': '3', 'HP': '3', 'Ability': 'Thieve 2', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Thieve', 'Ability_Parameters': 2, 'Ability_Trigger': 'Trigger', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Smoke Bomber": {'Name': 'Smoke Bomber', 'Rarity': 'U', 'Cost': 'GGG', 'Class': 'Rge', 'Type': 'Unit', 'Attack': '2', 'HP': '3', 'Ability': 'Debuff target unit -2/0', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [-2, 0], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Dagger Flurry": {'Name': 'Dagger Flurry', 'Rarity': 'U', 'Cost': 'AG', 'Class': 'Rge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Deal 1 Damage to all opp units', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Damage', 'Ability_Parameters': [1, 'AllOpp'], 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Distraction Tactic": {'Name': 'Distraction Tactic', 'Rarity': 'R', 'Cost': 'AAG', 'Class': 'Rge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Debuff all opp units -2/0', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [-2, 0, 'AllOpp'], 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Coin Spray": {'Name': 'Coin Spray', 'Rarity': 'R', 'Cost': 'GGGGGG', 'Class': 'Rge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Deal 4 damage to all opp units', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Damage', 'Ability_Parameters':  [4, 'AllOpp'], 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Corpse Looter": {'Name': 'Corpse Looter', 'Rarity': 'C', 'Cost': 'GGG', 'Class': 'Rge', 'Type': 'Unit', 'Attack': '2', 'HP': '2', 'Ability': 'Whenever a unit dies gain 1 gold', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Gold', 'Ability_Parameters': 1, 'Ability_Trigger': 'Trigger', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Arcane Surge": {'Name': 'Arcane Surge', 'Rarity': 'C', 'Cost': 'AA', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Channel 3', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Channel', 'Ability_Parameters': 3, 'Ability_Trigger': 'Cast', 'Additional_Costs': 'Wizard', 'Additional_Costs_Parameters': [3]},
	"Flame Flare": {'Name': 'Flame Flare', 'Rarity': 'R', 'Cost': 'AAA', 'Class': 'Mge', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Deal 3 Damage to all units', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Damage', 'Ability_Parameters': [3, 'All'], 'Ability_Trigger': 'Cast', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Spell Slinger": {'Name': 'Spell Slinger', 'Rarity': 'U', 'Cost': 'AG', 'Class': 'Mge', 'Type': 'Unit', 'Attack': '0', 'HP': '2', 'Ability': 'Whenever you cast a spell deal 1 damage to opponent', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Damage', 'Ability_Parameters': [1, 'CastSpell', 'OppPlayer'], 'Ability_Trigger': 'Trigger', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Champion": {'Name': 'Champion', 'Rarity': 'R', 'Cost': 'GGGG', 'Class': 'Knt', 'Type': 'Unit', 'Attack': '4', 'HP': '4', 'Ability': 'On Play: Rally 4', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Rally', 'Ability_Parameters': 4, 'Ability_Trigger': 'Cast', 'Additional_Costs': 'Merchant', 'Additional_Costs_Parameters': [4]},
	"Blade of Glory": {'Name': 'Blade of Glory', 'Rarity': 'U', 'Cost': 'AAG', 'Class': 'Knt', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Buff a unit +5/+2', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [5, 2], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Suit of Armor": {'Name': 'Suit of Armor', 'Rarity': 'C', 'Cost': 'GG', 'Class': 'Knt', 'Type': 'Spell', 'Attack': '', 'HP': '', 'Ability': 'Buff a unit +0/+4', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Buff', 'Ability_Parameters': [0, 4], 'Ability_Trigger': 'Target', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
	"Recruiter": {'Name': 'Recruiter', 'Rarity': 'U', 'Cost': 'GG', 'Class': 'Knt', 'Type': 'Unit', 'Attack': '2', 'HP': '1', 'Ability': 'Activate: Rally 1', 'Art': 'Sprites/card_placeholder.png', 'Ability_Function': 'Rally', 'Ability_Parameters': 1, 'Ability_Trigger': 'Cast', 'Additional_Costs': 'Merchant', 'Additional_Costs_Parameters': [1]},
	"Soldier": {'Name': 'Soldier', 'Rarity': 'T', 'Cost': '', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': '', 'Art': 'Sprites/Squire.png', 'Ability_Function': '', 'Ability_Parameters': [], 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
}

var WORKER_CARD_DB = {
	"Worker": {'Name': 'Worker', 'Cost': '', 'Class': 'Gen', 'Type': 'Work', 'Attack': '', 'HP': '', 'Ability': 'Produce 1 Gold', 'Art': 'Sprites/Merchant.png', 'Additional_Costs': '', 'Additional_Costs_Parameters': []}
}

var PLAYER_CARD_DB = {
	"Knight": {'Name': 'Knight', 'Type': 'Player', 'HP': '20', 'Art': 'Sprites/New_Sprites/Knight-2.png'},
	"Rogue": {'Name': 'Rouge', 'Type': 'Player', 'HP': '20', 'Art': 'Sprites/New_Sprites/Rogue-2.png'},
	"Mage": {'Name': 'Mage', 'Type': 'Player', 'HP': '20', 'Art': 'Sprites/New_Sprites/Mage-2.png'}
}

var TOKEN_DB = {
	"Soldier": {'Name': 'Soldier', 'Rarity': 'T', 'Cost': '', 'Class': 'Gen', 'Type': 'Unit', 'Attack': '1', 'HP': '1', 'Ability': '', 'Art': 'Sprites/Squire.png', 'Ability_Function': '', 'Ability_Parameters': [], 'Ability_Trigger': '', 'Additional_Costs': '', 'Additional_Costs_Parameters': []},
}
